# Omakase Ruby styling for Rails
require: rubocop-rails

inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3
  Exclude:
    - '*.html.erb'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'db/schemas.rb'
    - scripts.rb

Style/Documentation:
  Enabled: false

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: true

Style/IdenticalConditionalBranches:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - spec/**/*
    - test/**/*
    - db/**/*
    - Rakefile
    - Gemfile
    - app/channels/application_cable/connection.rb
    - app/helpers/application_helper.rb
    - app/jobs/application_job.rb
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
    - app/controllers/application_controller.rb

Style/ClassAndModuleChildren:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - double_quotes

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Metrics/BlockLength:
  Max: 150

Layout/HashAlignment:
  Enabled: true

Layout/LineLength:
  Max: 190
  Exclude:
    - 'app/controllers/dashboard/members_controller.rb'

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/InverseOf:
  Enabled: true

