default: &default
  adapter: postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS) { 5 } %>
  username: <%= ENV.fetch["POSTGRES_USER"] { 'postgres' } %>
  hist:     <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  port:     <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>

development:
  <<: *default
  host:     localhost
  username: postgres
  password: postgres
  port: 5432
  database: spacedevs_developmentx

test:
  <<: *default
  host:     localhost
  username: postgres
  database: spacedevs_test

production:
  primary: &primary_production
    <<: *default
    # database: <%= ENV["POSTGRES_DBNAME"] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>

  cache:
    <<: *primary_production
    database: spacedevs_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: spacedevs_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: spacedevs_production_cable
    migrations_paths: db/cable_migrate
