default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: spacedevs_development

test:
  <<: *default
  host:     localhost
  username: postgres
  password: postgres
  database: spacedevs_test

production:
  primary: &primary_production
    <<: *default
    host:     <%= ENV["DB_HOST"] %>
    username: <%= ENV["POSTGRES_USER"] %>
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    database: <%= ENV["POSTGRES_DB"] %>
