default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  database: spacedevs_development

test:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  database: <%= ENV.fetch("POSTGRES_DB", "spacedevs_test") %>

production:
  primary: &primary_production
  <<: *default
  host: <%= ENV.fetch("DB_HOST") %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  database: <%= ENV.fetch("POSTGRES_DB") %>

cache:
  <<: *primary_production
  database: spacedevs_production_cache
  migrations_paths: db/cache_migrate

queue:
  <<: *primary_production
  database: spacedevs_production_queue
  migrations_paths: db/queue_migrate

cable:
  <<: *primary_production
  database: spacedevs_production_cable
  migrations_paths: db/cable_migrate
