service: spacedevs

# image: ghcr.io/seu-usuario/minhaapp:latest

servers:
  web:
    hosts:
      - RAILS_WEB_HOST

proxy: false

# registry:
#   server:
#     - CONTAINER_REGISTRY_SERVER
#   username:
#     - CONTAINER_REGISTRY_USER
#   password:
#     - CONTAINER_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD

  clear:
    RAILS_ENV: production
    SOLID_QUEUE_IN_PUMA: false
    DB_HOST: spacedevs-db

asset_path: /rails/public/assets

builder:
  arch: amd64
  args:
    RUBY_VERSION: system

ssh:
  user: deploy

accessories:
  db:
    image: postgres:17.4
    host: spacedevs-db
    env:
      secret:
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    files:
      - config/init.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
