test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

mgc:
  service: S3
  endpoint: https://br-ne1.magaluobjects.com/spacedevs-storage
  access_key_id: <%= Rails.application.credentials.dig(:mgc, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:mgc, :secret_access_key) %>
  bucket: <%= Rails.application.credentials.dig(:mgc, :bucket) %>
  region: <%= Rails.application.credentials.dig(:mgc, :region) %>
